merryhime/dynarmic

include/dynarmic/dynarmic.h
src/backend_x64/block_of_code.cpp
src/backend_x64/block_of_code.h
src/backend_x64/interface_x64.cpp

Unused since the switch to Xbyak

dynarmic: Remove poison_memory ClearCache parameter

---

src/frontend/translate/translate_arm/status_register_access.cpp
src/frontend/translate/translate_arm/translate_arm.h
tests/arm/fuzz_arm.cpp

The test for this instruction is very peculiar. As the instruction's behavior depends on the value of the CPSR, we generate a MSR instruction after each SEL instruction to change the CPSR.

Implemented the ARM SEL instruction, with tests.

---

src/frontend/translate/translate_arm/extension.cpp

ARM: Implemented UXTB16.

---

src/backend_x64/reg_alloc.cpp
src/backend_x64/reg_alloc.h

Noticed slight improvement in profiling. Reduced hotpath samples.
The linked list is probably better suited for these random queries.
std::vector:
https://godbolt.org/g/nU8Pg6
std::forward_list:
https://godbolt.org/g/r2o1FH

Improved performance of reg_alloc

---

src/frontend/A64/decoder/a64.inc
src/frontend/A64/translate/impl/simd_crypto_three_register.cpp

SM3TT1B is essentially the same as SM3TT1A, with the only difference being how the initial TT1 value is calculated.

A64: Implement SM3TT1B

---

.travis.yml
.travis/build-aarch64-linux/build.sh
.travis/build-aarch64-linux/deps.sh
.travis/build-aarch64-linux/docker.sh
.travis/build-aarch64-linux/run.sh
src/CMakeLists.txt
src/backend/A64/emitter/a64_emitter.cpp
src/backend/A64/emitter/a64_emitter.h
src/backend/A64/emitter/arm_common.h
src/backend/A64/emitter/code_block.h
src/common/math_util.h
src/frontend/A64/translate/impl/impl.cpp

successor to #352 
I apologize for the glaring issues in that last PR, I was rushed for time that day and wanted early feedback.
Everything mentioned in the last PR should be resolved now 👍 
Any changes out of the backend area were to resolve compiler warnings or add things to common that dolphin's emitter needs.
A *much cleaner* dolphin diff can be found here:
https://github.com/BreadFish64/dolphin/commit/b5c7ff44679c0b28ccb515d66a2f56c477b46182

Preliminary changes to add aarch64 backend (round 2)

---

src/ir_opt/constant_propagation_pass.cpp

Multiplication operations can currently be folded if:
1. Both arguments are known constant values
2. Either operand is zero (in which case the result is also zero)
3. Either operand is one (in which case the result is the non-one operand).
We could also technically fold on the cases where:
4. `x * -1 -> -x`
5. `-1 * y -> -y`
but I'm not certain what the best way for doing that would be currently (from an API point of view)

constant_propagation_pass: Fold Mul32 and Mul64 cases where applicable

---

src/ir_opt/constant_propagation_pass.cpp

We can fold division operations if:
1. The divisor is zero, then we can replace the result with zero (as this is how ARM platforms expect it).
2. Both values are known, in which case we can just do the operation and store the result
3. The divisor is 1, in which case just return the other operand.
Like multiplication, this has a similar case where we can fold a negative case, namely a negative divisor of `1`:
4. `x / -1` → `-x`
However this can be handled after more trivial constant propagation is out of the way that doesn't require directly manipulating the opcode stream.

constant_propagation_pass: Fold division operations where applicable

---

src/ir_opt/constant_propagation_pass.cpp

These optimizations can also apply to the 64-bit variants of the shift opcodes; we just need to check if the instruction has an associated pseudo-op before performing the 32-bit variant's specifics.
While we're at it, we can also relocate the code to its own function like the rest of the cases to keep organization consistent.

constant_propagation_pass: Add 64-bit variants of shifts to the pass

---

externals/catch/catch.hpp

Keeps the unit testing library up to date. Changelogs [here](https://github.com/catchorg/Catch2/releases).

externals: Update catch to v2.4.1

---

tests/A32/fuzz_arm.cpp
tests/A32/test_thumb_instructions.cpp

Makes the changed code more consistent with the surrounding code.

dynarmic_tests: Remove inconsistent spacing

---

src/ir_opt/constant_propagation_pass.cpp

These are also reasonably trivial to fold away when applicable.
Specifically, if the operand is zero or all bits are set, we can just directly replace the instruction with the operand, since a swap would essentially be a no-op in these cases. In the case the operand is a different raw immediate, we can just perform the swap directly and replace the instruction with the constant value.
(force pushes were just improving the commit message)

constant_propagation_pass: Fold byte reversal opcodes where applicable

---

tests/A32/skyeye_interpreter/skyeye_common/vfp/vfp_helper.h

Makes the lines of code slightly nicer to read.

tests/.../vfp_helper: Amend use of the comma operator

---

externals/xbyak/readme.md
externals/xbyak/readme.txt
externals/xbyak/sample/bf.cpp
externals/xbyak/sample/static_buf.cpp
externals/xbyak/sample/test0.cpp
externals/xbyak/sample/test_util.cpp
externals/xbyak/sample/toyvm.cpp
externals/xbyak/test/jmp.cpp
externals/xbyak/test/sf_test.cpp
externals/xbyak/xbyak/xbyak.h
externals/xbyak/xbyak/xbyak_mnemonic.h
externals/xbyak/xbyak/xbyak_util.h

Keeps the external library up to date.

externals/xbyak: Update xbyak to 5.76

---

tests/unicorn_emu/a32_unicorn.cpp
tests/unicorn_emu/a32_unicorn.h

Makes the interface consistent with the A64Unicorn class.

tests/unicorn_emu: Add getters and setters for PC/SP

---

src/frontend/A64/decoder/a64.inc
src/frontend/A64/translate/impl/simd_scalar_x_indexed_element.cpp

We can trivially extend MultiplyByElement() to handle this case.

A64: Implement scalar double/single precision FMULX (by element)

---

src/frontend/A64/decoder/a64.inc
src/frontend/A64/translate/impl/simd_three_same_extra.cpp

Provides a naive implementation of FCADD and FCMLA

A64: Implement FCADD and FCMLA

---

src/common/fp/fused.cpp
src/common/fp/op/FPRSqrtEstimate.cpp
src/common/fp/op/FPRSqrtEstimate.h
src/common/fp/op/FPRSqrtStepFused.cpp
src/common/fp/op/FPRecipStepFused.cpp
src/common/fp/rounding_mode.h

Just removes a few unnecessary inclusions

common/fp: Remove unnecessary includes

---

src/CMakeLists.txt
src/backend/x64/emit_x64_floating_point.cpp
src/common/fp/op.h
src/common/fp/op/FPConvert.cpp
src/common/fp/op/FPConvert.h
src/frontend/A32/translate/translate_arm/vfp2.cpp
src/frontend/A64/decoder/a64.inc
src/frontend/A64/translate/impl/floating_point_data_processing_one_register.cpp
src/frontend/A64/translate/impl/impl.h
src/frontend/A64/translate/impl/simd_scalar_two_register_misc.cpp
src/frontend/A64/translate/impl/simd_two_register_misc.cpp
src/frontend/ir/ir_emitter.cpp
src/frontend/ir/ir_emitter.h
src/frontend/ir/opcodes.inc

Gotta love non-IEEE rounding mode handling.

A64: Implement scalar and vector variants of FCVTXN

---

src/frontend/A64/translate/impl/floating_point_conversion_integer.cpp

This just transfers values between vector registers and general-purpose registers with no conversions performed, so this is trivial to add support for half-precision to.

A64: Enable FMOV (general) for half-precision floating point

---

src/frontend/A64/decoder/a64.inc
src/frontend/A64/translate/impl/simd_vector_x_indexed_element.cpp

With this, all of the instructions introduced with ARMv8.3-CompNum have an implementation.

A64: Implement FCMLA's indexed element variant

---

src/frontend/A64/decoder/a64.inc
src/frontend/A64/translate/impl/simd_scalar_three_same.cpp

Implements the scalar variant in terms of the vector variant for the time being.

A64: Implement SQRDMULH's scalar vector variant

---

src/CMakeLists.txt
src/frontend/A32/decoder/arm.inc
src/frontend/A32/disassembler/disassembler_arm.cpp
src/frontend/A32/translate/translate_arm/divide.cpp
src/frontend/A32/translate/translate_arm/misc.cpp
src/frontend/A32/translate/translate_arm/multiply.cpp
src/frontend/A32/translate/translate_arm/reversal.cpp
src/frontend/A32/translate/translate_arm/translate_arm.h
tests/A32/fuzz_arm.cpp

Now that Unicorn is in place, these can all be implemented, since we're not limited by an ARMv6K interpreter.

A32: Handle all ARM-mode arithmetic and data processing instructions added in ARMv6T2 and ARMv7

---

src/backend/x64/emit_x64_vector.cpp

Performs a full 128-bit bit-reversal using only two instructions.
First by reversing all the bits of each byte using a galois matrix
multiplication(vgf2p8affineqb, GNFI. Added in Icelake), and then by reversing the bytes
themselves(pshufb, ssse3).
This PR relies on #554 
If you don't have Icelake-level hardware. It is possible to run the tests against non-native architectures using Intel's [Software Development Emulator](https://software.intel.com/content/www/us/en/develop/articles/intel-software-development-emulator.html) to simulate the ISA extensions that you do not have natively.
```
% sde64 -icl -sse-sde -- ./dynarmic_tests
CPU has MMX
CPU has MMX2
CPU has CMOV
CPU has SSE
CPU has SSE2
CPU has SSE3
CPU has SSSE3
CPU has SSE41
CPU has SSE42
CPU has POPCNT
CPU has AESNI
CPU has OSXSAVE …
```

emit_x64_vector: GNFI+SSSE3 implementation of EmitVectorReverseBits

---

src/CMakeLists.txt
src/frontend/A32/decoder/thumb32.inc
src/frontend/A32/translate/impl/thumb32_long_multiply.cpp
src/frontend/A32/translate/impl/translate_thumb.h

Fills out another category of unimplemented instructions

thumb32: Implement long multiply and divide instructions

---

src/frontend/A64/decoder/a64.inc

Keeps the instruction listing up to date.

a64: Add v8.6 instruction encoding additions

---

src/dynarmic/frontend/A32/decoder/thumb32.inc
src/dynarmic/frontend/A32/translate/impl/a32_translate_impl.h
src/dynarmic/frontend/A32/translate/impl/thumb32_load_store_dual.cpp

Note that those are ARMv8 additions to the Thumb instruction set.

thumb32: Implement LDA and STL

---

src/dynarmic/backend/exception_handler_macos.cpp

Caught by UBSan.  I don't think this has a meaningful performance impact (especially since the thread state doesn't include floating-point/vector registers), but I haven't tested it for performance.

exception_handler_macos: Avoid undefined behavior due to accessing misaligned pointer
