src/CMakeLists.txt, src/backend_x64/interface_x64.cpp, src/frontend/arm/PSR.h, src/frontend/arm_types.h, tests/arm/fuzz_arm.cpp, tests/arm/fuzz_thumb.cpp
Should be helpful later on when other modes and such are supported.
At the moment I've just made it proxy through existing functions in the LocationDescriptor class since I wasn't sure what the best way of doing that would be while maintaining the return-by-value interface for LocationDescriptor instances.
=> arm: Add PSR helper type

src/backend_x64/emit_x64.cpp, src/backend_x64/emit_x64.h, src/frontend/ir/ir_emitter.cpp, src/frontend/ir/ir_emitter.h, src/frontend/ir/opcodes.inc, src/frontend/translate/translate_arm/parallel.cpp
The x64 implementation uses the SSSE3 instruction PSHUFB.
A non-SSE fallback is provided in case the CPU doesn't support it.
=> Implemented the ARM UHADD8 instruction.

src/backend_x64/emit_x64.cpp
Use a 64-bit register to hold the values so that we don't end up interpreting them as signed values.
=> VFP: Fixed the VCVT behavior when converting from unsigned 32-bit values

src/backend_x64/emit_x64.cpp, src/backend_x64/reg_alloc.cpp, src/backend_x64/reg_alloc.h, src/frontend/ir/microinstruction.cpp, src/frontend/ir/microinstruction.h, src/ir_opt/verification_pass.cpp
Makes the operation a part of the direct interface.
I've kept the name as is, but would it be preferable to rename it to `DecrementUseCount()`?
=> microinstruction: Make use_count private

src/backend_x64/reg_alloc.cpp
=> reg_alloc: Remove unnecessary breaks after returns

include/dynarmic/dynarmic.h, src/CMakeLists.txt, src/backend_x64/emit_x64.cpp, src/backend_x64/emit_x64.h, src/backend_x64/interface_x64.cpp, src/common/address_range.h, src/frontend/ir/basic_block.cpp, src/frontend/ir/basic_block.h, src/frontend/translate/translate_arm.cpp, src/frontend/translate/translate_thumb.cpp, tests/arm/fuzz_arm.cpp
This implements `EmitX64::InvalidateCacheRange`, which invalidates the cache range passed to it. `Jit::Impl` tracks a queue of ranges to invalidate, instead of a single boolean `clear_cache_required`.
Also, I renamed `code_ptr` in `BlockDescriptor` to `entrypoint` ~~to make this PR harder to merge~~ for readability.
=> Ranged cache invalidation

src/CMakeLists.txt
When including fmtlib as a header only library in dynarmic, downstream
projects cannot include fmtlib as a static library without getting
linker errors. This change make dynarmic use the static library version
of fmtlib when DYNARMIC_NO_BUNDLED_FMT is set
=> Link against static fmtlib when DYNARMIC_NO_BUNDLED_FMT is set

src/common/cast_util.h
Given we use `std::aligned_storage_t`, we don't need to specify `typename` here. If we used `std::aligned_storage`, then we would need to.
=> cast_util: Remove unnecessary typename

src/frontend/ir/microinstruction.cpp, src/frontend/ir/microinstruction.h
Previously this instruction was always eliminated, resulting in incorrect values for TPIDR_EL0.
=> A64: The A64SetTPIDR IR instruction writes to a system register and should not be eliminated by the dead code elimination pass.

src/frontend/ir/microinstruction.cpp
These were forgotten when the opcodes were added.
Feel free to let me know if others should be added here.
=> microinstruction: Add missing FP scalar opcodes to ReadsFromFPSCR() and WritesToFPSCR()

externals/xbyak/readme.md, externals/xbyak/readme.txt, externals/xbyak/sample/bf.cpp, externals/xbyak/sample/protect-re.cpp, externals/xbyak/test/jmp.cpp, externals/xbyak/test/make_512.cpp, externals/xbyak/test/rip-label-imm.cpp, externals/xbyak/xbyak/xbyak.h, externals/xbyak/xbyak/xbyak_mnemonic.h
Keeps the library up to date and notably adds a convenience function for creating labels, and fixes a case of incorrect encodings being used.
```cpp
* 2018/Sep/04 ver 5.71 L() returns a new label instance
* 2018/Aug/27 ver 5.70 support setProtectMode() and DontUseProtect for read/exec setting
* 2018/Aug/24 ver 5.68 fix wrong VSIB encoding with vector index >= 16(thanks to petercaday)
```
=> externals: Update Xbyak to 5.71

externals/xbyak/gen/avx_type.hpp, externals/xbyak/gen/gen_code.cpp, externals/xbyak/readme.md, externals/xbyak/readme.txt, externals/xbyak/test/make_512.cpp, externals/xbyak/xbyak/xbyak.h, externals/xbyak/xbyak/xbyak_mnemonic.h
Fixes a few incorrect encodings. From the changelog:
- 2018/Sep/19 ver 5.73 fix evex encoding of vpslld, vpslldq, vpsllw, etc for (reg, mem, imm8)
- 2018/Sep/19 ver 5.72 fix the encoding of vinsertps for disp8N(Thanks to petercaday)
=> externals: Update Xbyak to 5.73

src/frontend/decoder/decoder_detail.h
Fixes decoding for 64-bit instructions.
Edit: Does not help/apply to any currently supported ARM versions (since all are 32-bit length or below), it's for future-proofing should such an arch be supported.
=> decoders: Cast to correctly-sized type before shifting

src/backend/x64/reg_alloc.cpp, src/frontend/ir/value.cpp, src/frontend/ir/value.h
This'll make it slightly nicer to do basic constant folding for 32-bit and 64-bit variants of the same IR opcode type. By that, I mean it's possible to inspect immediate values without a bunch of conditional checks beforehand to verify that it's possible to call GetU32() or GetU64, preventing code duplication.
=> value: Move ImmediateToU64() to be a part of Value's interface

src/frontend/ir/value.cpp, src/frontend/ir/value.h, src/ir_opt/constant_propagation_pass.cpp
Referenced in #401 that I'd open a PR for other convenience functions suggested in it. Notably, a signed variant to `GetImmediateAsU64()`. This also adds three other convenience functions, which are:
- IsSignedImmediate()
- IsUnsignedImmediate()
These would be useful for testing for values without the need to always do:
```cpp
if (x.IsImmediate() && x.GetImmediateAsU64() == ...)
```
- IsZero()
Does what it says. This is added simply because zero is the most common constant to test against in arithmetic, and is almost always a no-op or has some other beneficial quality to it, so it can have its own compact shorthand.
=> Add several convenience functions to the Value class

src/ir_opt/constant_propagation_pass.cpp
Adds folding for more of the extension opcodes. Now that we also have `GetImmediateAsS64()` function, we can also handle the sign-extension opcodes as well.
=> constant_propagation_pass: Extend folding of sign-extension/zero-extension opcodes

src/frontend/A64/decoder/a64.inc, src/frontend/A64/translate/impl/impl.h
Keeps the table up to date with the ARM specification.
=> a64: Add ARMv8.4+ instructions encodings to the encoding table

src/frontend/A64/translate/impl/floating_point_conversion_integer.cpp
fltsize is only ever set to 16 on branch that immediately returns, there
is no point in checking it again, as the condition is always true.
https://github.com/MerryMage/dynarmic/blob/52e646408fffccc26a03383adeafb0afc435dde0/src/frontend/A64/translate/impl/floating_point_conversion_integer.cpp#L82-L83
=> Remove always-true condition

tests/fuzz_util.cpp
This can just be a simple direct return without a separated declaration and assignment.
=> fuzz_util: Simplify result return in InstructionGenerator's Generate() function

src/backend/x64/a64_emit_x64.cpp
Given these are quite small, we can avoid the need to heap allocate here.
=> a64_emit_x64: Convert std::vector instances in GenFastmemFallbacks() to std::array

src/common/bit_util.h, tests/A32/skyeye_interpreter/skyeye_common/armstate.cpp
These are quite general functions, so they can just be moved into common instead of recreating a namespace here in the interpreter.
=> common: Move byte swapping functions to bit_utils.h

src/ir_opt/constant_propagation_pass.cpp
These are quite trivial to fold, given it just involves shifting or truncating the retrieved value.
=> constant_propagation_pass: Handle folding for Least/MostSignificant{Bit, Byte, Half, Word} opcodes

README.md
The example incorrectly uses `jit` and not `cpu`.
=> Correct README (`jit` to `cpu`)

tests/unicorn_emu/a32_unicorn.cpp
MemoryRead8() takes a u32, but we were passing the result of a `u32 + size_t` operation, which is 64-bit on 64-bit platforms. This results in a truncation warning.
=> a32_unicorn: Silence a truncation warning within UnmappedMemoryHook()

externals/catch/catch.hpp
Keeps the unit testing library up to date.
Changelog is [here](https://github.com/catchorg/Catch2/releases)
=> externals: Update catch to v2.5.0

tests/A32/fuzz_arm.cpp
This was introduced within 6f6f60c61b2137780102c75841441f760d3cc3fc, however, the relevant code that it was used with has since been removed, making the include unnecessary.
=> tests/A32/fuzz_arm: Remove unused Unix-specific include

src/frontend/A32/ir_emitter.cpp, src/frontend/A32/ir_emitter.h, src/frontend/A64/ir_emitter.cpp, src/frontend/A64/ir_emitter.h
In both IR emitters, these functions don't actually modify instance state, so they can be marked with a const qualifier.
=> frontend/{A32, A64}/ir_emitter: Mark PC() and AlignPC() as const-qualified member functions

include/dynarmic/A32/context.h, src/backend/x64/a32_interface.cpp
Provides a more "correct" move constructor/assignment operator, since these relevant functions shouldn't throw exceptions.
Has the benefit of playing nicely with std::move_if_noexcept and other noexcept library facilities (if they're ever useful)
=> backend/x64/a32_interface: Mark Context move constructor and move assignment as noexcept

externals/catch/catch.hpp
Keeps the unit testing library up to date.
Changelog [here](https://github.com/catchorg/Catch2/releases)
=> externals: Update Catch to 2.6.1

src/frontend/A32/translate/translate_arm/branch.cpp, src/frontend/A32/translate/translate_arm/coprocessor.cpp, src/frontend/A32/translate/translate_arm/data_processing.cpp, src/frontend/A32/translate/translate_arm/exception_generating.cpp, src/frontend/A32/translate/translate_arm/extension.cpp, src/frontend/A32/translate/translate_arm/load_store.cpp, src/frontend/A32/translate/translate_arm/misc.cpp, src/frontend/A32/translate/translate_arm/multiply.cpp, src/frontend/A32/translate/translate_arm/packing.cpp, src/frontend/A32/translate/translate_arm/parallel.cpp, src/frontend/A32/translate/translate_arm/reversal.cpp, src/frontend/A32/translate/translate_arm/saturated.cpp, src/frontend/A32/translate/translate_arm/status_register_access.cpp, src/frontend/A32/translate/translate_arm/synchronization.cpp, src/frontend/A32/translate/translate_arm/translate_arm.h, src/frontend/A32/translate/translate_arm/vfp2.cpp
Mainly just inverts conditionals related to:
```cpp
if (ConditionPassed) {
<lots of code>
}
```
to unindent stuff and make it similar to how the A64 side of things lays out everything. I've kept everything separate to make it nicer to review, though most of it is just the same thing across several files. I can also squash this down to a single commit if it's preferable for merging that way.
=> A32/translate_arm: Formatting/tidying up

tests/A32/fuzz_arm.cpp, tests/A32/fuzz_thumb.cpp, tests/A32/test_thumb_instructions.cpp, tests/A32/testenv.h
Makes the data member consistent with the A64 test environment.
=> tests/a32/testenv: Make A32TestEnv's code_mem member a std::vector

src/CMakeLists.txt, src/frontend/A64/decoder/a64.inc, src/frontend/A64/translate/impl/impl.h, src/frontend/A64/translate/impl/load_store_no_allocate_pair.cpp
LDNP and STNP indicate that a memory access is non-temporal/streaming (i.e. unlikely to be repeated), allowing data caching to not be performed. However, given this is only a hint, we can treat these two instructions as regular LDP and STP instructions for the time being.
=> A64: Implement LDNP/STNP

src/frontend/A64/translate/impl/simd_three_same_extra.cpp
An overly strong enforcement that I mistakenly introduced in #439. Rather than straight-up treating them as undefined, we can fall back to an interpreter in this case in the meantime until we support half-precision floating point.
=> A64: Fall back to interpreting for FCADD and FCMLA half-precision variants

src/common/bit_util.h
These four functions can be made constexpr with no issue.
=> common/bit_util: Mark a few functions as constexpr

src/frontend/A64/decoder/a64.inc, src/frontend/A64/translate/impl/impl.h
Gives these instructions better categorical labeling.
=> A64: Rearrange flag format/manipulation instructions

src/CMakeLists.txt, src/backend/x64/a64_emit_x64.cpp, src/frontend/A64/decoder/a64.inc, src/frontend/A64/ir_emitter.cpp, src/frontend/A64/ir_emitter.h, src/frontend/A64/translate/impl/system_flag_format.cpp, src/frontend/A64/translate/impl/system_flag_manipulation.cpp, src/frontend/ir/microinstruction.cpp, src/frontend/ir/opcodes.inc, src/ir_opt/a64_get_set_elimination_pass.cpp
Implements two of the four instructions from the ARMv8.4-CondM featureset, and all of the instructions from the ARMv8.5-CondM featureset in a naive manner.
If there's a preferable approach that doesn't make use of directly exposing of the raw values of the NZCV flag values I can change the instructions over to using that instead.
=> A64: Implement CFINV, RMIF, AXFlag and XAFlag

src/common/fp/op/FPConvert.cpp, src/common/fp/unpacked.h
These match the equivalent pseudocode within the ARMv8 reference manual, which will be necessary for half-precision floating-point support.
This also makes use of them within FPConvert.
=> common/fp/unpacked: Add FPRoundCV and FPUnpackCV

src/common/fp/info.h
Puts the necessary info struct in place for further use.
=> common/fp/info: Add specialization of FPInfo for half-precision floating point

src/common/fp/process_nan.cpp, src/common/fp/unpacked.cpp, src/common/fp/unpacked.h
Adds u16 instantiations for the core functions required by other functions. This is necessary to further support half-precision floating point.
=> common/fp: Minor adjustments for half-precision floating point support

src/backend/x64/emit_x64_floating_point.cpp, src/common/fp/op/FPRecipExponent.cpp, src/common/fp/unpacked.cpp, src/frontend/A64/decoder/a64.inc, src/frontend/A64/translate/impl/simd_scalar_two_register_misc.cpp, src/frontend/ir/ir_emitter.cpp, src/frontend/ir/ir_emitter.h, src/frontend/ir/microinstruction.cpp, src/frontend/ir/opcodes.inc, src/frontend/ir/value.h
Implements FRECPX and closes some holes in the half-precision unpacking.
=> A64: Implement FRECPX's half-precision floating-point variant

src/frontend/A64/decoder/a64.inc, src/frontend/A64/translate/impl/impl.h, src/frontend/A64/translate/impl/simd_scalar_x_indexed_element.cpp
These can be implemented in terms of the vector IR opcodes.
=> A64: Implement SQRDMULH and SQDMULL's scalar indexed variants

src/backend/x64/emit_x64_floating_point.cpp, src/common/fp/op/FPConvert.cpp, src/common/fp/unpacked.h, src/frontend/A64/translate/impl/floating_point_data_processing_one_register.cpp, src/frontend/A64/translate/impl/simd_two_register_misc.cpp, src/frontend/ir/ir_emitter.cpp, src/frontend/ir/ir_emitter.h, src/frontend/ir/microinstruction.cpp, src/frontend/ir/opcodes.inc
Knocks out a handful of fallbacks to the interpreter.
On top of implementing half-precision floating-point paths for the relevant instructions, this also fixes two bugs that slipped through in the FPUnpackCV and FPConvert implementations (my bad).
=> A64: Handle half-precision floating point in floating-point FCVT, FCVTL, and FCVTN

src/backend/x64/emit_x64_floating_point.cpp, src/frontend/A64/translate/impl/floating_point_data_processing_one_register.cpp, src/frontend/ir/ir_emitter.cpp, src/frontend/ir/ir_emitter.h, src/frontend/ir/opcodes.inc
Knocks out a few more trivial cases where we previously treated half-precision variants as unallocated encodings.
=> A64: Handle half-precision floating point in FABS, FNEG, and scalar FMOV

externals/catch/catch.hpp
Keeps the unit testing library up to date.
Changelog [here](https://github.com/catchorg/Catch2/releases)
=> externals: Update catch to 2.7.0

src/backend/x64/emit_x64_vector.cpp, src/common/fp/op/FPRecipExponent.cpp
There were two cases where negative signed left shifts could occur (which are undefined behavior). This prevents those cases by casting to unsigned before the shift to indicate that said shifts are desirable.
=> {common/fp, backend/x64}: Prevent undefined left shifts where applicable

src/frontend/A64/decoder/a64.inc, src/frontend/A64/translate/impl/simd_scalar_shift_by_immediate.cpp
This can be handled in terms of the vector variant for the time being.
=> A64: Implement scalar variant of SQSHL (immediate)

src/frontend/A64/decoder/a64.inc, src/frontend/A64/translate/impl/simd_scalar_shift_by_immediate.cpp
Like SQSHL's immediate scalar variant, we can also implement UQSHL's immediate scalar variant in terms of the vector variant for the time being.
=> A64: Implement UQSHL (immediate)'s scalar variant

src/CMakeLists.txt
This allows for cleaner integration of dynarmic as a library into other projects. Currently, the recommended solution appears to be `add_subdirectory`ing dynarmic into the parent project, but this leaks parent configuration into dynarmic and causes unnecessary rebuilds of dynarmic.
With this change, a file named `dynarmic-config.cmake` will be created as part of the dynarmic build process, so an external dynarmic build tree (when added to CMAKE_PREFIX_PATH) can be imported into other projects using a simple `find_package(dynarmic REQUIRED)`. Coincidentally, and totally not the reason I'm proposing this change, this is how the package manager Conan imports dependencies.
=> CMakeLists: Allow importing dynarmic build trees into other CMake projects

src/frontend/A64/translate/impl/simd_copy.cpp, src/frontend/A64/translate/impl/simd_extract.cpp, src/frontend/A64/translate/impl/simd_scalar_shift_by_immediate.cpp, src/frontend/A64/translate/impl/simd_scalar_two_register_misc.cpp, src/frontend/A64/translate/impl/simd_scalar_x_indexed_element.cpp, src/frontend/A64/translate/impl/simd_three_same_extra.cpp, src/frontend/A64/translate/impl/simd_vector_x_indexed_element.cpp
These are cases that are defined as reserved within the ARMv8 reference manual, so we can handle them as such instead of as unallocated encodings.
While this doesn't actually change emulated behavior, it does at least allow the JIT to generate the more appropriate exception.
=> A64: Handle reserved instruction cases more specifically where applicable

src/ir_opt/a32_constant_memory_reads_pass.cpp, src/ir_opt/a32_get_set_elimination_pass.cpp, src/ir_opt/a64_callback_config_pass.cpp, src/ir_opt/verification_pass.cpp
Makes the immutable state within the passes more explicit.
=> ir_opt: Mark locals as const where applicable

src/frontend/A64/translate/impl/impl.cpp
To a reader this might look particularly strange, given the function itself has a void return value, but this is actually valid, given the function in the return statement also has a void return value.
This instead alters it to be a little easier to parse and potentially be a little less confusing at a glance.
=> A64/impl: Reorganize peculiar void use in V_scalar

src/backend/x64/a32_emit_x64.cpp, src/backend/x64/emit_x64.cpp, src/backend/x64/oparg.h, src/frontend/A32/translate/translate_arm.cpp, src/frontend/A64/translate/impl/impl.cpp, src/frontend/ir/ir_emitter.cpp
We can just use the self-documenting assertion for indicating unreachable paths, instead of manually passing false and providing a message.
=> general: Replace unreachable-imitating assertions with UNREACHABLE()

src/backend/x64/a32_jitstate.cpp, src/backend/x64/a32_jitstate.h, src/backend/x64/a64_jitstate.cpp, src/backend/x64/a64_jitstate.h, src/frontend/A32/location_descriptor.h, src/frontend/A64/location_descriptor.h, src/frontend/ir/location_descriptor.h
Generally hash functions shouldn't throw exceptions. It's also a requirement for the standard library-provided hash functions to not throw exceptions.
An exception to this rule is made for user-defined specializations, however we can just be consistent with the standard library on this to allow these to potentially play nicer with it.
=> general: Mark hash functions as noexcept

src/frontend/A64/translate/impl/load_store_exclusive.cpp, src/frontend/A64/translate/impl/load_store_multiple_structures.cpp, src/frontend/A64/translate/impl/load_store_register_immediate.cpp, src/frontend/A64/translate/impl/load_store_register_pair.cpp, src/frontend/A64/translate/impl/load_store_register_register_offset.cpp, src/frontend/A64/translate/impl/load_store_single_structure.cpp
Makes bracing consistent, and variables const where applicable to be consistent with the rest of the codebase.
In most bracing cases, they'd need to be added to conditionals that would involve checking stack pointer alignment in the future anyways.
=> load_store_*: Make bracing consistent and variables const where applicable

src/common/fp/info.h, src/common/fp/op/FPMulAdd.cpp, src/common/fp/op/FPRSqrtEstimate.cpp, src/common/fp/op/FPRSqrtStepFused.cpp, src/common/fp/op/FPRecipEstimate.cpp, src/common/fp/op/FPRecipExponent.cpp, src/common/fp/op/FPRecipStepFused.cpp, src/common/fp/op/FPRoundInt.cpp, src/common/fp/process_nan.cpp, src/common/fp/unpacked.cpp
While initially done to potentially prevent creating bugs due to C++ having a silly type-promotion mechanism involving types < sizeof(int) and unsignedness, given that the bulk of these functions' usages are on exit paths, these can return the correct type to avoid the need to cast at every usage point.
=> common/fp/info: Make half-precision info struct functions return correctly sized types

src/frontend/ir/basic_block.cpp, src/frontend/ir/basic_block.h
Avoids inclusions where applicable. Notably, doing so allows making changes to the memory pool interface (should it be necessary), without having it ripple across the whole IR emitter framework.
=> ir/basic_block: Forward declare headers where applicable

src/frontend/ir/cond.h
This is no longer used by anything in the codebase, so it can be removed.
=> frontend/ir/cond: Remove unused invert() function

tests/A32/fuzz_arm.cpp
Introduces the same fuzzing mechanism used by the AArch64 code for fuzzing instruction implementations, getting rid of the need to manually specify the instruction generator sequences—replacing it with an instruction blacklist instead.
Much of this change originates from a previous patch made by Mary. This just makes it interact nicely with the alterations made to get Unicorn to cooperate properly.
=> a32/fuzz_arm: Use same fuzzing mechanism as AArch64

src/CMakeLists.txt, src/frontend/A64/translate/impl/impl.h, src/frontend/imm.h
Preparation to utilize the immediate type within the A32 backend as well, which will allow eliminating numerous type aliases like Imm4, Imm5, etc.
=> frontend: Move imm.h to the top-level directory of the frontends

src/frontend/A32/disassembler/disassembler_arm.cpp, src/frontend/A32/disassembler/disassembler_thumb.cpp, src/frontend/A32/translate/translate_arm.cpp, src/frontend/A32/translate/translate_arm/barrier.cpp, src/frontend/A32/translate/translate_arm/branch.cpp, src/frontend/A32/translate/translate_arm/coprocessor.cpp, src/frontend/A32/translate/translate_arm/data_processing.cpp, src/frontend/A32/translate/translate_arm/exception_generating.cpp, src/frontend/A32/translate/translate_arm/load_store.cpp, src/frontend/A32/translate/translate_arm/misc.cpp, src/frontend/A32/translate/translate_arm/packing.cpp, src/frontend/A32/translate/translate_arm/saturated.cpp, src/frontend/A32/translate/translate_arm/status_register_access.cpp, src/frontend/A32/translate/translate_arm/translate_arm.h, src/frontend/A32/translate/translate_arm/vfp2.cpp, src/frontend/A32/translate/translate_thumb.cpp, src/frontend/A32/types.h
Replaces type aliases of raw integral types with the more type-safe Imm template, like how the AArch64 frontend has been using it.
This makes the two frontends more consistent with one another.
=> A32: Replace immediate type aliases with the Imm template

src/CMakeLists.txt, src/frontend/A32/decoder/arm.inc, src/frontend/A32/disassembler/disassembler_arm.cpp, src/frontend/A32/translate/translate_arm/crc32.cpp, src/frontend/A32/translate/translate_arm/translate_arm.h
Implements the ARM-mode variants of the CRC32 instructions introduced within ARMv8. This is also one of the instruction cases where there is UNPREDICTABLE behavior that is constrained (we must do one of the options indicated by the reference manual).
In both documented cases of constrained unpredictable behavior, we treat the instructions as undefined (which is one of the options allowed by the reference manual).
=> A32: Implement ARM-mode CRC32 instructions

include/dynarmic/A32/config.h, src/CMakeLists.txt, src/frontend/A32/translate/translate_arm.cpp, src/frontend/A32/translate/translate_arm/hint.cpp, src/frontend/A32/translate/translate_arm/translate_arm.h
Mirrors the hooking functionality from the AArch64 frontend to make the behavior of both consistent.
=> A32: Allow hooking of hint instructions in ARM mode.

src/frontend/ir/ir_emitter.cpp, src/frontend/ir/ir_emitter.h
These aren't necessary anymore, now that the U32U64 overload exists.
=> frontend/ir/ir_emitter: Remove unnecessary logical shift overloads

include/dynarmic/A32/config.h, src/frontend/A32/decoder/arm.inc, src/frontend/A32/disassembler/disassembler_arm.cpp, src/frontend/A32/translate/translate_arm/hint.cpp, src/frontend/A32/translate/translate_arm/translate_arm.h, tests/A32/fuzz_arm.cpp
Extends PLD to also handle it's ARMv7 addition, PLDW. While we're at it, the hint instructions in the disassembler can have the `<unimplemented>` string removed from them, given we support hooking them now.
=> A32: Handle PLDW

include/dynarmic/A32/config.h, include/dynarmic/A64/config.h, src/frontend/A32/decoder/arm.inc, src/frontend/A32/decoder/thumb16.h, src/frontend/A32/decoder/thumb32.h, src/frontend/A32/disassembler/disassembler_arm.cpp, src/frontend/A32/disassembler/disassembler_thumb.cpp, src/frontend/A32/translate/translate_arm/hint.cpp, src/frontend/A32/translate/translate_arm/translate_arm.h, src/frontend/A32/translate/translate_thumb.cpp
Implements `NOP`, `SEV`, `SEVL`, `WFE`, `WFI`, and `YIELD` variants for Thumb-1. While we're in the same area, this also implements the ARM-mode variant of `SEVL`, given it's just as easy to implement as the Thumb-1 version.
=> A32: Implement Thumb-1 hint instructions

.travis/build-x86_64-macos/build.sh, include/dynarmic/A32/coprocessor.h, src/CMakeLists.txt, src/backend/x64/a32_emit_x64.cpp
Removes a boost header from the public includes in favor of using the standard-provided std::variant. Given we use std::optional in the header already, we can transition over to the std::variant from boost::variant.
With this removal, this makes all of our dependencies internal to the library itself.
=> A32/coprocessor: Remove boost from public interface

src/frontend/A32/decoder/arm.inc, src/frontend/A32/disassembler/disassembler_arm.cpp, src/frontend/A32/translate/translate_arm/misc.cpp, src/frontend/A32/translate/translate_arm/translate_arm.h
Fairly trivial. The lower-half analogue to MOVT.
=> A32: Implement ARM-mode MOVW

src/backend/x64/a32_jitstate.cpp, src/frontend/A32/location_descriptor.h
Ensures the alternate half-precision state is preserved within the location descriptors, which will be necessary when implementing the half-precision extensions for VFP and NEON.
=> A32/location_descriptor: Add AHP bit to the FPSCR mask

include/dynarmic/A64/config.h, src/backend/x64/a64_emit_x64.cpp
Instead of looking up the page table like:
table[addr >> 12][addr & 0xFFF]
We can use a global offset on the table to query the memory like:
table[addr >> 12][addr]
This saves two instructions on *every* memory access within the recompiler.
Thanks at skmp for the idea.
=> A64/x64: Create a global_offset optimization for the page table.

include/dynarmic/A32/config.h, src/backend/x64/a32_emit_x64.cpp
port of #505 to the A32 emitter
=>  A32/x64: Create a global_offset optimization for the page table

include/dynarmic/A64/a64.h, include/dynarmic/A64/config.h, include/dynarmic/A64/exclusive_monitor.h, src/backend/x64/a64_emit_x64.cpp, src/backend/x64/a64_emit_x64.h, src/backend/x64/a64_exclusive_monitor.cpp, src/backend/x64/a64_interface.cpp, src/backend/x64/a64_jitstate.h, src/frontend/A64/ir_emitter.cpp, src/frontend/A64/ir_emitter.h, src/frontend/A64/translate/impl/impl.cpp, src/frontend/A64/translate/impl/impl.h, src/frontend/A64/translate/impl/load_store_exclusive.cpp, src/frontend/A64/translate/impl/system.cpp, src/frontend/A64/translate/translate.h, src/frontend/ir/microinstruction.cpp, src/frontend/ir/microinstruction.h, src/frontend/ir/opcodes.inc, tests/A64/a64.cpp, tests/A64/testenv.h
This set of changes do the next things:
* Allow changing the dynarmic's interface processor Id.
* Add a new wall_clock_cntpct to remove redundant code when a host timer is used instead of a cycle timer.
* Refactor Exclusive memory to using both dynarmic's OG approach and QEMU's approach, thus eliminating false negative when one cpu core does a non-exclusive write on memory marked as exclusive in another cpu core.
* Add an Exceptional Exit for callbacks that exit dynarmic execution in unconventional ways. This is normally done when a thread sleeps/pauses on an SVC and wakes up later. Since the code cache may have changed or the thread was migrated to another interface, it isn't safe to return to dynarmic.
=> Set of changes to Exclusive Mem in A64 and Configuration

src/CMakeLists.txt, src/frontend/A32/decoder/asimd.h, src/frontend/A32/decoder/asimd.inc, src/frontend/A32/translate/impl/asimd_two_regs_shift.cpp, src/frontend/A32/translate/impl/translate_arm.h
Implements the following ASIMD shift instructions:
- VSHR
- VSRA
- VRSHR
- VRSRA
- VSHL
- VSRI
- VSLI
The rest of the shift instructions will be implemented in another PR to avoid cluttering up this PR, which is already large
=> A32: Implement several ASIMD shift instructions

include/dynarmic/A32/a32.h, src/backend/x64/a32_interface.cpp
This function is normally required for emulating certain OS mechanisms.
=> A32: Allow cleaning up exclusive state from the interface.

include/dynarmic/A64/config.h, src/backend/x64/a32_emit_x64.cpp, src/backend/x64/a64_emit_x64.cpp, tests/A32/test_arm_instructions.cpp, tests/A32/testenv.h, tests/A64/a64.cpp, tests/A64/testenv.h
Direct access to host (virtual) address space with ```fastmem``` offset, propagated from A32.
The goal is to delegate page table computation and page boundaries detection to the hardware.
**Benchmark**
From memory intensive sequential read/write
```
env.MemoryWrite32(0, 0x910004E7); // ADD X7, X7, 1
env.MemoryWrite32(4, 0x91002042); // ADD X2, X2, 8
env.MemoryWrite32(8, 0xF9400046); // LDR X6, [X2]
env.MemoryWrite32(12, 0x91002063); // ADD X3, X3, 8
env.MemoryWrite32(16, 0xF9000066); // STR X6, [X3]
env.MemoryWrite32(20, 0xF9400046); // LDR X6, [X2]
env.MemoryWrite32(24, 0xF9000066); // STR X6, [X3]
env.MemoryWrite32(28, 0xF9400046); // LDR X6, [X2]
env.MemoryWrite32(32, 0xF9000066); // STR X6, [X3]
env.MemoryWrite32(36, 0xF9400046); // LDR X6, [X2]
env.MemoryWrite32(40, 0xF9000066); // …
```
=> A64 fastmem

src/backend/x64/emit_x64_vector.cpp
Optimizes our byte-lane bit-shifts into a single-instruction galois field affine transformation.
An identity 8x8 bit-matrix represented as a 64-bit integer can itself be bit-shfited which can be used to arbitrarily shift the bits of each 8-bit lane left or right. At emit-time, the 64-bit matrix constant can be generated and emitted as an embedded broadcast to allow for a fast single-instruction version of unsigned(logical) bit-shifts and possibly the signed(arithmetic) bit-shifts and rotations.
=> emit_x64_vector: GNFI implementation of byte-lane shifts

src/backend/x64/emit_x64_vector.cpp
Should be shifting in _bytes_ of `0x80`. Not bits.
=> emit_x64_vector: Fix ArithmeticShiftRightByte zero_extend constant

src/frontend/A32/location_descriptor.h, src/frontend/A64/location_descriptor.h
Compare `single_stepping` with the other's value instead of comparing it
with the local value.
=> location_descriptor: Fix compare operator for single stepping

include/dynarmic/A32/config.h, include/dynarmic/A64/config.h, src/backend/x64/a32_emit_x64.cpp, src/backend/x64/a64_emit_x64.cpp
Add config entry to mask out the lower bits in page table pointers. This is intended to allow users of Dynarmic to pack small integers inside pointers and update the pair atomically without locks. These lower bits can be masked out due to the expected alignment in pointers inside the page table.
For example if pointers are guaranteed to be aligned to 8 bytes, the lower bits of all pointers in the page table will look like this:
```
... 7654 3210
nnn nnnn n000
```
These first 3 bits are guaranteed to be zero and can be used for arbitrary data as long as they are masked out when used.
yuzu in particular has 3 bits for attributes on a separate page table describing the state of the page (unmapped, mapped, cached, and others inherited from Citra currently unused). We have to be able to update …
=> backend/{a32,a64}_emit_x64: Add config entry to mask page table pointers

include/dynarmic/A32/config.h, src/backend/x64/a32_emit_x64.cpp
This is the same as 0f27368fdab3d2d1169e8dab14854e888bc9ce72, except for A32, as there are also 32-bit games that hit this issue (e.g. Megadimension Neptunia VII).
=> A32: Add hook_isb option.

src/CMakeLists.txt, src/frontend/A32/decoder/thumb32.h, src/frontend/A32/translate/impl/thumb32_misc.cpp, src/frontend/A32/translate/impl/translate_thumb.h, tests/A32/fuzz_thumb.cpp
Begins the addition of Thumb-2 instructions and extends the Thumb-1 harness to allow for Thumb-2 instruction generation and fuzzing.
=> thumb32: Implement miscellaneous category instructions

src/CMakeLists.txt, src/frontend/A32/decoder/thumb32.inc, src/frontend/A32/translate/impl/thumb32_multiply.cpp, src/frontend/A32/translate/impl/translate_thumb.h
Migrates over the five basic multiplication instructions. Will implement the others in a follow-up PR to keep this one small.
=> thumb32: Implement MLA/MLS/MUL/USAD8/USADA8

include/dynarmic/A64/config.h, src/CMakeLists.txt, src/backend/x64/a64_emit_x64.cpp, src/frontend/A64/decoder/a64.inc, src/frontend/A64/ir_emitter.cpp, src/frontend/A64/ir_emitter.h, src/frontend/A64/translate/impl/impl.h, src/frontend/A64/translate/impl/sys_ic.cpp, src/frontend/ir/microinstruction.cpp, src/frontend/ir/opcodes.inc, tests/A64/a64.cpp, tests/A64/testenv.h
I'm looking for a bit of feedback, so I thought I'd make a WIP pull request!
`ic ivau` expects an address argument, however `ic iallu` and `ic ialluis` invalidates all instruction caches and thus _doesn't_ expect an address argument.
So I'm not really sure how the signature should look for `InstructionCacheOperationRaised`. Should we wrap the `Vaddr` in a `std::optional`? I'm all ears! 😺 
Also, the test sucks. Shall I remove it, or is there a simpler way to test that the instructions are decoded correctly?
=> A64 IC Instructions

src/CMakeLists.txt, src/frontend/A32/decoder/thumb32.inc, src/frontend/A32/translate/impl/thumb32_data_processing_plain_binary_immediate.cpp, src/frontend/A32/translate/impl/translate_thumb.h
Gets the plain binary immediate files in place. Will follow this up by doing the saturation instructions within the same category
=> thumb32: Implement MOVT/MOVW 

src/frontend/A32/decoder/thumb32.inc, src/frontend/A32/translate/impl/thumb32_data_processing_register.cpp, src/frontend/A32/translate/impl/translate_thumb.h
Completes the register data processing category of instructions.
=> thumb32: Implement ASR, LSL, LSR, and ROR register variants

src/frontend/A32/decoder/thumb32.inc, src/frontend/A32/translate/impl/thumb32_load_word.cpp, src/frontend/A32/translate/impl/translate_thumb.h
Implements Thumb-2's variants of the LDR{T} instructions.
Following this PR, the halfword instructions will be implemented.
=> thumb32: Implement Thumb-2 LDR variants

src/frontend/A64/decoder/a64.inc
Adds the instructions introduced in FEAT_WFxT and FEAT_LS64/FEAT_LS64_V in ARMv8.7
=> a64: Add v8.7 instruction additions to the decoder

src/frontend/A32/decoder/thumb32.inc, src/frontend/A32/translate/impl/thumb32_data_processing_plain_binary_immediate.cpp, src/frontend/A32/translate/impl/translate_thumb.h
Now all the plain binary immediate instructions are implemented.
=> thumb32: Implement plain binary immediate ADR variants

src/CMakeLists.txt, src/frontend/A32/decoder/thumb32.inc, src/frontend/A32/translate/impl/thumb32_load_store_multiple.cpp, src/frontend/A32/translate/impl/translate_thumb.h
Implements all of the user-mode multiple load/store instructions.
With this all of the main load/store types are implemented, and the only thing left is the `Load/Store Dual, Load/Store Exclusive, Table Branch` category.
=> thumb32: Implement LDM/STM variants

src/backend/x64/block_of_code.cpp
- The current limits are being hit in yuzu with some games (e.g. newer updates of BotW and SSBU).
- Increasing this fixes slow-downs in these games due to code being recompiled.
Credit to @degasus for finding this problem.
=> backend: x64: block_of_code: Double the total code size.

src/backend/x64/a32_emit_x64.cpp, src/backend/x64/a64_emit_x64.cpp, src/backend/x64/emit_x64.cpp, src/backend/x64/emit_x64.h, src/backend/x64/perf_map.cpp
Both the far code and fast_dispatch_table_lookup were missing.
TODO: BlockOfCode::ClearCache also clears the perf file, however the trampolines are not generates. This leads to missing registered code.
=> backend/x64: Fix PerfMapRegister usages.

tests/cpu_info.cpp
Adds the Processor name and family information.
Compacts and formats the output a bit to be much more
concise. Sorts CPU features by alphabetical order. Mostly
to speed up `HostFeature` testing.
Before:
```
CPU has MMX
CPU has MMX2
CPU has CMOV
CPU has SSE
CPU has SSE2
CPU has SSE3
CPU has SSSE3
CPU has SSE41
CPU has SSE42
CPU has POPCNT
CPU has AESNI
CPU has OSXSAVE
CPU has PCLMULQDQ
CPU has AVX
CPU has FMA
CPU has RDTSCP
CPU has AVX2
CPU has BMI1
CPU has BMI2
CPU has LZCNT
CPU has INTEL
CPU has ENHANCED_REP
CPU has RDRAND
CPU has ADX
CPU has RDSEED
CPU has SMAP
CPU has HLE
CPU has RTM
CPU has F16C
CPU has MOVBE
CPU has AVX512F
CPU has AVX512DQ
CPU has AVX512CD
CPU has AVX512BW
CPU has AVX512VL
CPU has PREFETCHW
CPU has MPX
```
After:
```
Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz …
```
=> cpu_info: Add CPU Name, Family, compact output

src/dynarmic/backend/x64/a32_emit_x64.cpp, src/dynarmic/backend/x64/a32_emit_x64.h, src/dynarmic/backend/x64/a64_emit_x64.cpp, src/dynarmic/backend/x64/a64_emit_x64.h, src/dynarmic/backend/x64/a64_interface.cpp, src/dynarmic/interface/A32/config.h, src/dynarmic/interface/A64/config.h, tests/A32/test_arm_instructions.cpp, tests/A32/testenv.h, tests/A64/a64.cpp, tests/A64/testenv.h
This is a rebase of the fm branch. I've moved small hotfixes from the second commit to the first commit.
I've tested it a lot on yuzu, and it roughly provides a 15% speed over the page table approach.
@MerryMage Do you want to have this feature in master?
=> a64_emit_x64: Implement fastmem for A64 frontend for 8-64 bit reads/writes

src/dynarmic/backend/x64/a64_emit_x64.cpp
Sorry sorry sorry. Seems like I've just tested fastmem. Stupid copy&paste error.
=> fixup! a64/fastmem: Implement fastmem on 128 bit memory access.

src/dynarmic/backend/x64/a64_emit_x64.cpp, src/dynarmic/interface/A64/config.h, tests/A64/a64.cpp
We might want to allocate different sizes for each of them.
e.g. for the unsafe fastmem approach without bounds checking.
Or for using the full 48bit adress range (with mirrors) by allocating our real arena as close to 1<<47 as possible.
=> A64/config.h: Split fastmem and page_table options.

src/dynarmic/backend/x64/emit_x64_floating_point.cpp, src/dynarmic/backend/x64/emit_x64_vector_floating_point.cpp
This implementation exists within the unsafe optimization paths and utilize the 14-bit-precision `vrsqrt14*` and `vrcp14p*` instructions provided by AVX512F+VL. These are _more_ accurate than the fallback path and the current `rsqrt`-based unsafe code-path but still falls in line with what is expected of the `Unsafe_ReducedErrorFP` optimization flag, I think.
With `Unsafe_ReducedErrorFP`:
* Having AVX512 available will mean this function has **14** bits of precision
* fp64 and fp32 implementation is a single `vrsqrt14p{s,d}` instruction
* Not having AVX512 available will mean these functions have ~**11** bits of precision
* fp32 implementation is a single `rcpps` instruction
* fp64 implementation converts to fp32(`cvtpd2ps`), uses `rcpps`, and converts back up to fp64(`cvtps2pd`)
This …
=> emit_x64{_vector}_floating_point: Unsafe AVX512 implementation of Emit{RSqrt,Recip}Estimate

src/dynarmic/backend/x64/a32_interface.cpp, src/dynarmic/backend/x64/a64_interface.cpp, src/dynarmic/common/fp/unpacked.h, src/dynarmic/common/x64_disassemble.cpp, src/dynarmic/common/x64_disassemble.h, src/dynarmic/interface/A32/a32.h, src/dynarmic/interface/A64/a64.h
Adds the ability to get the disassembly that would've before been dumped to stdout as a vector of strings. I'm unfamiliar with this project so if I just walked into a minefield by copying the "dump" function don't hesitate to let me know. Also let me know if there's a more idiomatic approach here.
This information will be pulled into the [debugger I'm writing for yuzu](https://github.com/Avuxo/yuzu/tree/beato-debugger).  I tested it by linking against this version with yuzu and confirmed disassembly is output as expected.
=> Disassemble as vector of strings

src/dynarmic/frontend/A32/disassembler/disassembler_thumb.cpp
`fmt` 8.1.0 added more formatting checks and `Cond` can't be formatted directly now.
This shouldn't break compatibilities with `fmt` < `8.1.0` though, as I think it is very likely it was an accident that it passed compilation on any `fmt` version that is lower than `8.1.0` since `Cond` does not implement `operator<<` for `std::ostream` or `fmt::formatter`.
------
For an example of what error is thrown, here it is:
```
In file included from /app/include/fmt/format.h:48,
from /run/build/yuzu/externals/dynarmic/src/dynarmic/frontend/A32/disassembler/disassembler_thumb.cpp:9:
/app/include/fmt/core.h: In instantiation of ‘constexpr decltype (ctx.begin()) fmt::v8::detail::parse_format_specs(ParseContext&) [with T = Dynarmic::IR::Cond; ParseContext = fmt::v8::detail::compile_parse_context<char, …
```
=> disassembler_thumb: fix formatting issues with fmt 8.1.x

src/dynarmic/CMakeLists.txt, src/dynarmic/backend/x64/a32_emit_x64.h, src/dynarmic/backend/x64/a32_emit_x64_memory.cpp, src/dynarmic/backend/x64/a64_emit_x64.h, src/dynarmic/backend/x64/a64_emit_x64_memory.cpp, src/dynarmic/backend/x64/emit_x64_memory.h, src/dynarmic/backend/x64/exclusive_monitor.cpp, src/dynarmic/backend/x64/exclusive_monitor_friend.h, src/dynarmic/common/spin_lock.h, src/dynarmic/common/spin_lock_x64.cpp, src/dynarmic/common/spin_lock_x64.h, src/dynarmic/interface/A32/config.h, src/dynarmic/interface/A64/config.h, src/dynarmic/interface/exclusive_monitor.h, src/dynarmic/interface/optimization_flags.h
This emulates exclusive instructions with qemu/unicorn semantics, relying purely on cmpxchg. Note that this will obviously suffer from the [ABA problem](https://en.wikipedia.org/wiki/ABA_problem); however no user of this library uses the exclusive callbacks correctly in order to avoid this issue anyway.
=> Inline exclusive memory access operations

.github/workflows/aarch64.yml, externals/CMakeLists.txt
New commits often break Dynarmic when building it for Android (clang NDK compiler + Android headers).
As such, I think adding an Android (aarch64) build to the ci would be a good idea to prevent this from happening.
The Android build is not tested (only the linux gcc one is), but making sure it is able to build itself should already be enough from my point of view.
=> ci: Add Android aarch64 build

src/dynarmic/backend/x64/a32_interface.cpp, src/dynarmic/backend/x64/a64_interface.cpp, src/dynarmic/backend/x64/block_of_code.cpp, src/dynarmic/backend/x64/block_of_code.h, src/dynarmic/backend/x64/constant_pool.cpp
Reserve memory and commit in ~1MB chunks on Win32.
=> x64/block_of_code: Only commit minimum required memory

CMakeLists.txt
The reason why is explained in the comment.
=> CMakeLists: disable -Warray-bounds for GCC
